$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.IO.Compression.FileSystem
$root='D:\BTL_ML\10123154_BuiDangHuy_CDUTV'
$out=Join-Path $root 'docs\baocao.docx'
$tmp=Join-Path $root 'tools\report_openxml'
if(Test-Path $tmp){Remove-Item $tmp -Recurse -Force}
New-Item $tmp -ItemType Directory | Out-Null
New-Item (Join-Path $tmp '_rels') -ItemType Directory | Out-Null
New-Item (Join-Path $tmp 'word\_rels') -ItemType Directory -Force | Out-Null
New-Item (Join-Path $tmp 'word\media') -ItemType Directory -Force | Out-Null
function X([string]$s){[System.Security.SecurityElement]::Escape($s)}
$script:body=New-Object System.Text.StringBuilder
$script:rels=New-Object System.Text.StringBuilder
$script:rid=1
function P([string]$text,[string]$style='Normal'){$x=X $text;[void]$script:body.Append("<w:p><w:pPr><w:pStyle w:val='$style'/></w:pPr><w:r><w:t xml:space='preserve'>$x</w:t></w:r></w:p>")}
function Heading([string]$text,[int]$level){P $text ("Heading$level")}
function Tbl($headers,$rows){$s='<w:tbl><w:tblPr><w:tblBorders><w:top w:val="single"/><w:left w:val="single"/><w:bottom w:val="single"/><w:right w:val="single"/><w:insideH w:val="single"/><w:insideV w:val="single"/></w:tblBorders></w:tblPr>'; $all=@(,$headers)+$rows; foreach($row in $all){$s+='<w:tr>';foreach($cell in $row){$s+='<w:tc><w:p><w:r><w:t xml:space="preserve">'+(X ([string]$cell))+'</w:t></w:r></w:p></w:tc>'};$s+='</w:tr>'};$s+='</w:tbl>';[void]$script:body.Append($s)}
function Img([string]$file,[string]$caption){$src=Join-Path $root ('docs\figures\'+$file);if(!(Test-Path $src)){return};$id='rId'+$script:rid;$script:rid++;$target='media/'+$file;[void]$script:rels.Append("<Relationship Id='$id' Type='http://schemas.openxmlformats.org/officeDocument/2006/relationships/image' Target='$target'/>");Copy-Item $src (Join-Path $tmp ('word\media\'+$file));$cx=5486400;$cy=3657600;$drawing="<w:p><w:r><w:drawing><wp:inline xmlns:wp='http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing' xmlns:a='http://schemas.openxmlformats.org/drawingml/2006/main' xmlns:pic='http://schemas.openxmlformats.org/drawingml/2006/picture'><wp:extent cx='$cx' cy='$cy'/><wp:docPr id='$script:rid' name='$file'/><a:graphic><a:graphicData uri='http://schemas.openxmlformats.org/drawingml/2006/picture'><pic:pic><pic:nvPicPr><pic:cNvPr id='$script:rid' name='$file'/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed='$id' xmlns:r='http://schemas.openxmlformats.org/officeDocument/2006/relationships'/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x='0' y='0'/><a:ext cx='$cx' cy='$cy'/></a:xfrm><a:prstGeom prst='rect'><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>";[void]$script:body.Append($drawing);P $caption 'Caption'}
P 'BAO CAO DO AN HOC MAY CO BAN' 'Title';P 'CHAN DOAN UNG THU VU (LANH TINH / AC TINH)' 'Title';P 'Hoc phan Hoc may co ban (221180) - Lop 12523W.2' 'Subtitle';P 'Bui Dang Huy - 10123154';P 'Nguyen Vinh Phuc - 12523066';P 'Ngay cap nhat: 25/09/2026';P 'MUC LUC' 'Heading1';P '1. Gioi thieu bai toan va du lieu';P '2. Phan tich kham pha du lieu (EDA)';P '3. Xu ly du lieu';P '4. Huan luyen cac mo hinh';P '5. Danh gia va lua chon mo hinh';P '6. Dong goi mo hinh';P '7. Thiet ke he thong';P '8. Docker va trien khai';P '9. Kiem thu va hieu nang';P '10. Ket luan, han che va huong phat trien';P '11. Phan cong cong viec';P '12. Tai lieu tham khao'
Heading '1. GIOI THIEU BAI TOAN VA DU LIEU' 1;Heading '1.1. Bai toan' 2;P 'De tai xay dung he thong hoc may phan loai nhi phan mau khoi u vu thanh hai nhom lanh tinh (benign) va ac tinh (malignant). Target diagnosis co hai gia tri B va M; trong pipeline B duoc anh xa thanh 0 va M thanh 1. Muc tieu gom EDA, preprocessing khong roi ri du lieu, so sanh model, dong goi model.joblib, xay dung AI Service, Backend, Frontend, MongoDB va Docker Compose.';Heading '1.2. Nguon va quy mo du lieu' 2;P 'Dataset Breast Cancer Wisconsin (Diagnostic) Data Set duoc tai tu Kaggle, nguon goc UCI Machine Learning Repository, license CC BY-NC-SA 4.0. File dataset.zip chua data.csv.';Tbl @('Thuoc tinh','Gia tri') @(@('So mau','569'),@('So cot goc','33'),@('Feature dung cho model','30'),@('Benign B','357'),@('Malignant M','212'),@('Dong trung lap','0'),@('O thieu goc','569, deu o Unnamed: 32'));P 'Cot id chi la dinh danh va Unnamed: 32 la cot rong nen duoc loai bo. Feature gom cac nhom mean, se va worst.'
Heading '2. PHAN TICH KHAM PHA DU LIEU (EDA)' 1;P 'EDA xem phan bo nhan, thang do, missing values, tuong quan va kha nang phan biet hai lop.';Img 'eda1_target.png' 'Hinh 1. Phan bo hai lop diagnosis.';P 'Co 357 mau lanh tinh va 212 mau ac tinh, du lieu lech nhe. Dung stratify va theo doi Recall, Precision, F1, PR-AUC.';Img 'eda2_hist.png' 'Hinh 2. Histogram cac feature nhom mean.';P 'Feature co thang do khac nhau va mot so phan bo lech phai. Dung StandardScaler trong pipeline.';Img 'eda3_missing.png' 'Hinh 3. Ban do du lieu thieu.';P 'O thieu den tu Unnamed: 32; pipeline van giu SimpleImputer median de xu ly du lieu moi.';Img 'eda4_corr.png' 'Hinh 4. Ma tran tuong quan.';P 'radius_mean va perimeter_mean tuong quan khoang 0.998; giu du 30 feature de schema nhat quan va ghi nhan da cong tuyen.';Img 'eda5_box.png' 'Hinh 5. So sanh feature theo diagnosis.';P 'Nhom worst va concave points phan biet B va M ro hon.';Img 'eda6_pair.png' 'Hinh 6. Pairplot cac feature chinh.';P 'Hai lop tach kha ro nhung van co vung chong lan, do do thu ca model tuyen tinh va phi tuyen.'
Heading '3. XU LY DU LIEU' 1;P 'load_data doc data.csv tu zip, loai id va Unnamed: 32, loai dong trung, tach X/y va anh xa B -> 0, M -> 1. Du lieu chia train/test 80/20 voi stratify=y va random_state=42. Imputer va scaler nam trong Pipeline, chi fit tren tap train trong GridSearchCV de tranh data leakage. schema.json mo ta 30 feature, kieu, min/max, target va labels.'
Heading '4. HUAN LUYEN CAC MO HINH' 1;P 'Nam model duoc thu nghiem la Logistic Regression, KNN, SVM RBF, Decision Tree va Random Forest. Cung split, preprocessing, GridSearchCV, StratifiedKFold 5 folds va scoring F1. Metric gom Accuracy, Precision, Recall, F1, ROC-AUC va PR-AUC. Recall malignant quan trong vi false negative la bo sot mau ac tinh.'
Heading '5. DANH GIA VA LUA CHON MO HINH' 1;Tbl @('Model','Recall','Precision','F1','ROC-AUC','Size KB') @(@('Logistic Regression','0.9762','1.0000','0.9880','0.9977','2.4'),@('KNN','0.8571','0.9730','0.9114','0.9825','102.3'),@('SVM RBF','0.9762','1.0000','0.9880','0.9970','16.6'),@('Decision Tree','0.8333','0.8974','0.8642','0.9076','3.2'),@('Random Forest','0.9286','1.0000','0.9630','0.9965','89.4'));Img 'model_compare.png' 'Hinh 7. So sanh metric tren tap test.';Img 'model_overfit.png' 'Hinh 8. So sanh F1 train va test.';Img 'model_confusion.png' 'Hinh 9. Ma tran nham lan.';Img 'model_roc.png' 'Hinh 10. Duong ROC.';P 'Chon Logistic Regression C=0.1 vi Recall/F1/ROC-AUC cao, file nho 2.4 KB, toc do du doan thap va de giai thich. SVM co F1 tuong duong nhung lon hon; Random Forest tot nhung nang hon; KNN va Decision Tree co Recall thap hon.'
Heading '6. DONG GOI MODEL' 1;P '05_package chon Logistic Regression, huan luyen lai pipeline tren toan bo 569 mau va luu model.joblib. File chua SimpleImputer, StandardScaler va classifier. AI Service load model ngay khi khoi dong.';Tbl @('Artifact','Vai tro') @(@('model.joblib','Pipeline + classifier fit tren 569 mau'),@('schema.json','Hop dong feature/label cho FE, BE, AI'),@('metadata.json','Ten model, version, metric va library versions'))
Heading '7. THIET KE HE THONG' 1;P 'Frontend Nginx tao form tu schema va goi Backend qua /api. Backend Express validate, sinh request_id, goi AI Service va luu history MongoDB. AI Service FastAPI load model, validate lan hai va tra prediction/probability/model_version. MongoDB luu requestId, features, prediction, probability, modelVersion va createdAt. Endpoint Backend gom /health, /api/schema, /api/model-info, /api/predict, /api/history; AI gom /health, /model-info, /predict.'
Heading '8. DOCKER VA TRIEN KHAI' 1;P 'docker-compose.yml gom mongodb:7, ai-service, backend va frontend. MongoDB co volume va healthcheck; Backend chi khoi dong sau MongoDB va AI healthy; Frontend dung Nginx reverse proxy /api. Chay local bang Copy-Item .env.example .env va docker compose up --build. He thong da xac minh local voi bon service healthy/running; chua co public/tunnel.'
Heading '9. KIEM THU VA HIEU NANG' 1;P 'AI Service co 7 test pass; Backend co 8 test pass; Frontend node --check pass. Smoke test qua localhost:3000 thanh cong: HTTP 200, schema 30 feature, prediction qua Backend -> AI Service va history luu vao MongoDB. Chua thuc hien load test dong thoi nen chua cong bo p50/p95/throughput/error rate.'
Heading '10. KET LUAN, HAN CHE VA HUONG PHAT TRIEN' 1;P 'Project da hoan thanh quy trinh tu EDA, preprocessing, so sanh nam model, chon Logistic Regression, dong goi pipeline, API AI, Backend, Frontend, MongoDB va Docker Compose.';P 'Han che: dataset nho, chua dai dien moi quan the benh nhan; model chua kiem dinh lam sang; chua load test/public; MongoDB local khong mat khau chi phu hop hoc tap.';P 'Huong phat trien: du lieu ngoai tap huan luyen, kiem dinh doc lap, monitoring, auth, secret, CI/CD, deploy cloud va theo doi model drift.'
Heading '11. PHAN CONG CONG VIEC' 1;Tbl @('Thanh vien','Noi dung','Artifact') @(@('Bui Dang Huy - 10123154','ML, AI Service, Backend, Docker','ai-models/src, ai-models/service, app/backend'),@('Nguyen Vinh Phuc - 12523066','EDA, danh gia, Frontend, tai lieu','ai-models/colab, docs/figures, app/frontend'));P 'Bang phan cong can doi chieu voi lich su commit/merge truoc khi nop.';Heading '12. TAI LIEU THAM KHAO' 1;P '[1] Kaggle dataset: https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data';P '[2] UCI Repository: https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic';P '[3] Scikit-learn: https://scikit-learn.org/stable/';P '[4] FastAPI: https://fastapi.tiangolo.com/';P '[5] Docker: https://docs.docker.com/';P '[6] MongoDB: https://www.mongodb.com/docs/'
$document='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:body>'+[string]$script:body+'<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>'
$ct='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>'
$rels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'
$wrels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+[string]$script:rels+'</Relationships>'
$styles='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:pPr><w:jc w:val="center"/></w:pPr><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Subtitle"><w:name w:val="Subtitle"/><w:basedOn w:val="Normal"/><w:pPr><w:jc w:val="center"/></w:pPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="Heading 1"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="Heading 2"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="24"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Caption"><w:name w:val="Caption"/><w:basedOn w:val="Normal"/><w:pPr><w:jc w:val="center"/></w:pPr></w:style></w:styles>'
if(Test-Path $out){Remove-Item $out -Force};$zip=[System.IO.Compression.ZipFile]::Open($out,[System.IO.Compression.ZipArchiveMode]::Create);function Entry([string]$name,[string]$content){$e=$zip.CreateEntry($name);$w=New-Object IO.StreamWriter($e.Open(),[Text.UTF8Encoding]::new($false));$w.Write($content);$w.Dispose()};Entry '[Content_Types].xml' $ct;Entry '_rels/.rels' $rels;Entry 'word/document.xml' $document;Entry 'word/styles.xml' $styles;Entry 'word/_rels/document.xml.rels' $wrels;foreach($img in Get-ChildItem (Join-Path $root 'docs\figures\*.png')){$e=$zip.CreateEntry('word/media/'+$img.Name);$src=[IO.File]::OpenRead($img.FullName);$dst=$e.Open();$src.CopyTo($dst);$src.Dispose();$dst.Dispose()};$zip.Dispose();Remove-Item $tmp -Recurse -Force;Write-Output ('SAVED '+$out)
